### ISSUE TITLE
Improve error-handling

### ISSUE THREAD

**Issue by chrishelgert** [danielbayerlein/git-pick#3]
* says successfull, when merge-conflict and stay´s in failed branch
* stdout / stderr

**Comment by danielbayerlein** [comment]
See 4b29317161491633a8dbb945aa485200c092c16f

**Comment by chrishelgert** [comment]
nice once 👍

**Comment by danielbayerlein** [comment]
@danielbayerlein/git-pick 1.0.3 published 🎉
